apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
  namespace: ${K8S_APP_NAMESPACE}
spec:
  endpoint: ${APPCONFIG_ENDPOINT}
  auth:
    managedIdentityClientId: ${MY_MANAGED_IDENTITY_PRINCIPAL_ID}
  target:
    configMapName: configmap-created-by-appconfig-provider
