apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
  namespace: ${K8S_APP_NAMESPACE}
spec:
  connectionStringReference: config-service-secret 
  target:
    configMapName: configmap-created-by-appconfig-provider
